### PR TITLE
[DEBUG] added higher level debugging, [RE] Added historic feature

### PR DESCRIPTION
**Pull request by datatellers-devs**
Historic feature re-pulled (see #36), with additional debugging messages to investigate a possible bug

### CODE REVIEW

**Comment by datatellers-devs** [comment]
@Piiit no problem, will take care of that.

Didn't rebase before since it appears to be caused by two lines of code and thought you had tools on your side to fast-forward safely.

Will take care of it now

**Comment by bertolla** [comment]
Hi, the pull request is still failing because you forgot to solve the merge conflict you got in pom.xml. I tried to change it, but since i have no write access on your pull-requests I can't.
You have something like this in your pull-request:
```xml
                <dependency>
                        <groupId>it.bz.idm.bdp</groupId>
                        <artifactId>dc-interface</artifactId>
<<<<<<< HEAD
                        <version>[1.2.4,2.0.0)</version>
=======
                        <version>1.2.4</version>
>>>>>>> [MINOR][OPTIMIZATION] remove unused pom requirement
                </dependency>
```
This  <version>[1.2.4,2.0.0)</version> is our current version range and it would be nice if you could use this

**Comment by datatellers-devs** [comment]
Hey @bertolla, sorry had issues with the rebase since in the meantime i had the folder structure changed and that for some reason bugged Atom's conflicts plugin. Should be dealt with by now! Feel free to close if so!

**Comment by Piiit** [comment]
@bertolla Is issue #2 solved with this merging now?

**Pull request merged**
