### PR TITLE
First implementation of Hydrogen Data Collector (rebased) 

### PR DESCRIPTION
**Pull request by edp-progetti**
First implementation of Hydrogen Data Collector, containing reading of data from source (IIT Web service), transformation to internal DTO, transformation to BDP DTOs, push data to BDP.

### CODE REVIEW

**Comment by bertolla** [comment]
The test failed, because the test class itself has compilation errors. Please fix this so I can merge the pull request.

**Comment by edp-progetti** [comment]
Fixed compilation error

**Comment by bertolla** [comment]
After integrating the pull request I couldn't deploy it on the testserver, because the tests still failed.
I noticed that the test `testFetchData` returned 1 station and the test expected 4. Wouldn't it be better to just check that the number of returned stations is >0, to avoid that on every small change of the data returned the test fails? Or is it a must that the number of stations is always 4? Can you @edp-progetti make it so that the tests really only fail when they returned data is not conform to what we need?

**Comment by edp-progetti** [comment]
Changed test according to your suggestion, we simply check that the data are fetched and that there is some data present.

**Pull request merged**
