### PR TITLE
add call to getDateOfLastRecord in order to send only new data to the Data Hub, refine test cases and documentation

### PR DESCRIPTION
**Pull request by edp-progetti**
This pull request contains:
- implementation of the logic that avoid push of measures already sento to the Data Hub. This behaviour can be configured changing value of env parameter;
- implementation of the logic that pushes measurements in a single call instead of in separated calls, one for each station. Also this  behaviour can be configured changing value of env parameter;
- refined test cases;
- refined documentation;
- removed unused or commented code

### CODE REVIEW

**Comment by bertolla** [comment]
@edp-progetti 
Hi, I noticed that lately your pull requests are failing with our CI(see red cross up there). First I thought other datacollectors still have problems but it's for 2 reasons. The first reason is that your working on master instead of development branch and therefore there can be conflicts and the second reason is that your not rebasing your fork on our latest changes.
To do this you need to start from your local repository by stashing uncommitted changes(if you even have that):
`git stash`
Checkout the development branch(if you haven't already done that), and apply all the changes you made on master:
```
git checkout development
git rebase master
```
(I tried this with your fork and it worked like a charm)

Now you need to bring your fork up to date with all our changes(this should be done before you create a pull request). Add the main repository as a remote(I called this remote noi) 
```
git remote add noi https://github.com/idm-suedtirol/bdp-commons.git
```
You need to this only the first time, with `git remote -v` you should see all existing remotes

Fetch the noi remote, checkout **your** branch and rebase on the noi development branch(normally a merge would be better but in your case there are 0 conflicts and we can keep a clean commit history). Check if everything is fine with log.
```
git fetch noi
git checkout development
git rebase noi/development
git log
```
Since you have rewritten (git)history you will need to force push your changes:
`git push --force`

Your fork should now be up to date and you just need to do the pull-request as you did in the past. Don't forget to choose your **development branch** as the from branch.

For further documentation we have created a guide in our documentation: https://opendatahub.readthedocs.io/en/latest/contributors.html

**Comment by edp-progetti** [comment]
Hi Patrick,
thank you for the instructions, I followed them and everything worked fine.
I am now working on my development branch that is in sync with idm-suedtirol development branch.

What is the best way to proceed now?
Should I close the pull request #62 and then open a new one that theoretically should not give any problem?

Thanks,
Marco.

**Comment by bertolla** [comment]
> Should I close the pull request #62 and then open a new one that theoretically should not give any problem?

Exactly, it's important that you choose your forks development branch as from and our development branch as To, than everything should work fine.

**Comment by edp-progetti** [comment]
Pull request must be opened from dev branch of our fork. We close this one.

**Pull request closed without merging**
